#!/bin/bash
set -euxo pipefail
# Starts a roving client that connects to the example roving server
#
# NOTE: must be run from the roving/ directory

unamestr=$(echo $(uname) | tr '[:upper:]' '[:lower:]')

# This is temporary until we figure out how to fix this crash
export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1

rm -rf examples/client/output
bazel build //cmd/client
mkdir -p examples/client
cd examples/client
../../bazel-bin/cmd/client/${unamestr}_amd64_stripped/client \
  -server-address ${MASTERURL}:1414
